version: "3"

services:
  master:
    build: .
    entrypoint: top -b
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./master_postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master_init.sh:/docker-entrypoint-initdb.d/master_init.sh
      - ./data/master/.ssh:/var/lib/postgresql/.ssh
      - ./data/replica/.ssh/id_rsa.pub:/var/lib/postgresql/.ssh/authorized_keys
      - master_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  replica:
      build: .
      environment:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      volumes:
        - ./backup_init.sh:/docker-entrypoint-initdb.d/backup_init.sh
        - ./data/replica/.ssh:/var/lib/postgresql/.ssh
        - ./data/master/.ssh/id_rsa.pub:/var/lib/postgresql/.ssh/authorized_keys
        - backup_db:/var/lib/postgresql/backup_db/
      ports:
        - 25432:5432

volumes:
  master_data:
  backup_db: